Repository tc39/proposal-temporal, pull requests merged in 2020-11, with the labels that each got.

#1089 add github actions workflows
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: meta

#1096 remove .travis.yml
  .travis.yml
Labels: meta

#1148 Update ambiguity.md with latest conversion syntax
  docs/ambiguity.md
Labels: awaiting-author

#1189 Speed up Test262 tests and improve test output
  .github/workflows/test.yml
  .gitignore
  polyfill/ci_test.sh
  polyfill/test/debugResults.py
  polyfill/test/parseResults.js
  polyfill/test/parseResults.py
Labels: awaiting-author

#1216 Clarify ZDT docs for `from` behavior of date/time fields
  docs/zoneddatetime.md
Labels: documentation
