Repository tc39/proposal-temporal, pull requests merged in 2021-09, with the labels that each got.

#1688 Normative: Optimize calls into user code in InterpretISODateTimeOffset
  polyfill/lib/ecmascript.mjs
  polyfill/test/ZonedDateTime/constructor/from/balance-negative-time-units.js
  polyfill/test/ZonedDateTime/prototype/with/balance-negative-time-units.js
  spec/timezone.html
  spec/zoneddatetime.html
Labels: needs plenary input

#1836 Tighten ISO parsing of month and day values
  polyfill/lib/regex.mjs
  polyfill/test/regex.mjs
Labels: no-spec-text

#1843 Add @@toStringTag to TS types
  polyfill/index.d.ts
Labels: typescript, no-spec-text
