Repository tc39/proposal-temporal, pull requests merged in 2022-02, with the labels that each got.

#2033 Work around Firefox bug with `'gregory'` calendar era names
  polyfill/lib/calendar.mjs
Labels: non-prod-polyfill, no-spec-text

#2034 Handle number-less DateTimeFormat Hebrew month
  polyfill/lib/calendar.mjs
Labels: non-prod-polyfill, no-spec-text

#2024 Add meeting minutes from December and January
  meetings/agenda-minutes-2021-12-09.md
  meetings/agenda-minutes-2022-01-06.md
  meetings/agenda-minutes-2022-01-20.md
Labels: no-spec-text

#2056 Update return type of `Calendar.p.fields` in docs and TS types to match the spec
  docs/calendar.md
  polyfill/index.d.ts
Labels: documentation, typescript, no-spec-text

#2067 Update docs about month/day standardization
  docs/strings.md
Labels: documentation, no-spec-text

#2072 Remove incorrect text from `withCalendar` docs
  docs/plaindate.md
  docs/plaindatetime.md
Labels: documentation, no-spec-text

#2051 Unbreak validStrings.mjs
  .github/workflows/test.yml
  polyfill/test/validStrings.mjs
Labels: no-spec-text
